name: Connect Deployment
application: namelyconnect
triggers:
- jenkins:
    job: "Connect/job/master"
    master: "namely-jenkins"
    propertyFile: "build.properties"
stages:
- account: int-k8s
  name: "Migrate INT"
  refId: "1"
  runJob:
    manifestFile: test-deployment.yml
    container: # override default command defined in the manifest
      command:
        - bundle
        - exec
        - rake
        - db:migrate
- account: int-k8s
  name: "Deploy to INT"
  refId: "2"
  reliesOn:
    - "1"
  deploy:
    manifestFile: test-deployment.yml
    maxRemainingASGS: 2 # total amount of replica sets to keep around afterwards before deleting
    scaleDown: true
    stack: web # primarily for labeling purposes on the created resources
    strategy: redblack
    targetSize: 2 # this is the total amount of replicas for the deployment
